### ISSUE TITLE
Is it possible to set bigger font size?

### ISSUE THREAD

**Issue by pypetey** [agusmakmun/django-markdown-editor#12]
Hi,

Is it possible to set bigger font size in editor in django-admin?

**Comment by agusmakmun** [comment]
If I following [this issue](https://stackoverflow.com/q/21900938/6396981), I think you can custom css also;

```python
class MyModelAdmin(admin.ModelAdmin):
    ....

    class Media:
        css = {'all': ('css/my-custom-ace.css', )}
```

and then, `css/my-custom-ace.css`:

```css
#martor-my_field_name { /* #martor-description */
  font-size: 16pt
}
```
