### ISSUE TITLE
Newer Django dark mode looks horrible when combined with Martor

### ISSUE THREAD

**Issue by yatahaze** [agusmakmun/django-markdown-editor#168]
The newer version of Django where the admin supports auto dark mode, it looks quite bad when dark mode is initiated on admin pages that have martor fields. 

It looks like everything still functions, it just looks bad.

**Comment by yatahaze** [comment]
If anyone needs an immediate fix:

`MARTOR_ALTERNATIVE_CSS_FILE_THEME = "fix-martor.css"`

```css
@media (prefers-color-scheme: dark) {
    body {
        background-color: black!important;
    }
}
```
