### ISSUE TITLE
Bootstrap styles conflicting with Django Admin

### ISSUE THREAD

**Issue by bendavis78** [agusmakmun/django-markdown-editor#185]
When using martor in the admin, it causes collapsible fieldsets to be hidden due to the following bootstrap css rule.

```css
.collapse:not(.show) {
    display: none;
}
```

This can be worked around by adding an overriding CSS rule, however, such a workaround should not be necessary.
