### ISSUE TITLE
martor doesn't render level 2 header?

### ISSUE THREAD

**Issue by Ikaroshu** [agusmakmun/django-markdown-editor#64]
Hi,
I'm trying to integrate martor to my project, I found h2 header does not seem to display properly in the preview, it is highlighted with a blue bar. I don't know why. Where could be the problem?
<img width="584" alt="屏幕快照 2019-03-29 12 17 58" src="https://user-images.githubusercontent.com/13895960/55250934-5f6cb600-521d-11e9-8369-92c32a784388.png">
Thank you!

**Comment by Ikaroshu** [comment]
It seems only shows in admin page.
I tried with martor_demo, h2 is also not rendered properly.

**Comment by agusmakmun** [comment]
It because css of django admin `base.css`

```css
.module h2, .module caption, .inline-group h2 {
    margin: 0;
    padding: 8px;
    font-weight: 400;
    font-size: 13px;
    text-align: left;
    background: #79aec8;    # here the css
    color: #fff;
}
```

I suggest you **_to force this css_** at file of [`static/martor/css/martor-admin.css`](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/static/martor/css/martor-admin.css) and compile it as [`static/martor/css/martor-admin.min.css`](https://github.com/agusmakmun/django-markdown-editor/blob/master/martor/static/martor/css/martor-admin.min.css)
